# Generated by Django 4.0.4 on 2022-05-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.postcomment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('CMPLN', 'Complaint'), ('FMLY', 'Family'), ('FRNDS', 'Friends'), ('HBBS', 'Hobbies'), ('LV', 'Love'), ('OTHR', 'Other'), ('SCHL', 'School'), ('SPRTS', 'Sports')], max_length=10),
        ),
    ]
