# Generated by Django 4.0.4 on 2022-05-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0002_alter_like_post_alter_like_post_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post_comment',
        ),
    ]
