# Generated by Django 4.0.4 on 2022-05-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0004_alter_like_owner_alter_post_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.postcomment'),
        ),
    ]
