# Generated by Django 4.0.4 on 2022-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0006_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='body',
            field=models.CharField(max_length=666),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_text',
            field=models.CharField(max_length=255),
        ),
    ]
