# Generated by Django 4.0.4 on 2022-05-22 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConfessionsApp', '0007_alter_confession_body_alter_post_post_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
