# Generated by Django 4.0.4 on 2022-05-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0009_alter_confession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='confession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfessionsApp.confession'),
        ),
    ]
