# Generated by Django 4.0.4 on 2022-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0010_like_confession'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
