# Generated by Django 4.0.4 on 2022-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0013_alter_confession_date_alter_confession_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
