# Generated by Django 4.0.4 on 2022-07-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfessionsApp', '0016_post_edited_post_edited_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
